### ISSUE TITLE
Can you make a variant of `new` that does not panic?

### ISSUE THREAD

**Issue by jymchng** [khonsulabs/lockedbox#1]
Hi, thank you for your excellent work.

I am writing [`sosecrets-rs`](https://github.com/jymchng/sosecrets-rs) which has a `Secret<T>` type that guarantees at compile time that the inner `T` cannot be exposed more than `N`, an integer number of times.

I am thinking of providing `mlock()` with my constructor such that `T` memory is locked as well. I am thinking of using this crate as it takes care of the destructor.

However, I am uncomfortable with the fact that the constructor panics, is it okay if you do one that does not panic?

**Comment by ecton** [comment]
I've released v0.1.2 with `LockedBox::try_new` based on this request. Thank you for suggesting the feature!
